# Generated by Django 6.0.3 on 2026-05-25 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('esta_finalizada', models.BooleanField(default=False)),
                ('fecha_finalizada', models.DateTimeField(blank=True, null=True)),
                ('total_ticket', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tienda')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('comprado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.maestroproducto')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.listacompra')),
            ],
        ),
    ]
