# Generated by Django 6.0.3 on 2026-04-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_maestroproducto_precio_ultimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlista',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
