# Generated by Django 6.0.3 on 2026-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_itemlista_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacompra',
            name='fecha_finalizada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
