# Generated by Django 6.0.3 on 2026-04-08 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_listacompra_fecha_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlista',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
